### ISSUE TITLE
TypeError during training startup

### ISSUE THREAD

**Issue by michelecafagna26** [shentianxiao/language-style-transfer#25]
I got this error on training startup that I can't figure out.
Data is formatted as described in the README with the correct naming, 1 line per sentence.
used : 
-nvidia-docker
-tensorflow-gpu 1.13.1

Traceback (most recent call last):
  File "style_transfer.py", line 228, in <module>
    model = create_model(sess, args, vocab)
  File "style_transfer.py", line 192, in create_model
    model = Model(args, vocab)
  File "style_transfer.py", line 120, in __init__
    zeros, ones = self.labels[:half], self.labels[half:]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 597, in _slice_helper
    _check_index(s.stop)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 516, in _check_index
    raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor 'truediv_1:0' shape=<unknown> dtype=float64>

**Comment by michelecafagna26** [comment]
Fixed using python 2 and tensorflow 1.3.0
